spring.application.name=dogiadung



spring.datasource.url=jdbc:sqlserver://127.0.0.1:1433;databaseName=CHGiaDung;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Mushii24@
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
Using generated security password: fe7af222-771e-4355-8d38-16a6dc555ed8

#This generated password is for development use only. Your security configuration must be updated before running your application in production.
# ================== FILE UPLOAD CONFIG ==================
# Đường dẫn thư mục lưu ảnh (bạn có thể thay đổi)
file.upload-dir=D:/uploads/products

# Kích thước file tối đa (10MB)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Cho phép Spring Boot phục vụ ảnh từ thư mục ngoài
#spring.web.resources.static-locations=classpath:/static/,file:${file.upload-dir}/



#spring.application.name=dogiadung
#
## ================== DATABASE ==================
#spring.datasource.url=jdbc:sqlserver://127.0.0.1:1433;databaseName=CHGiaDung;encrypt=true;trustServerCertificate=true
#spring.datasource.username=sa
#spring.datasource.password=Mushii24@
#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
#
## JPA
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#
## ================== SECURITY (TẮT MẶC ĐỊNH) ==================
#spring.boot.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
#
## ================== FILE UPLOAD ==================
#file.upload-dir=D:/uploads/products
#spring.web.resources.static-locations=classpath:/static/,file:${file.upload-dir}/
#spring.servlet.multipart.max-file-size=10MB
#spring.servlet.multipart.max-request-size=10MB
#
#server.port=8080
