spring.application.name=dogiadung
file.upload-dir=D:/project4/uploads/products
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=CHGiaDung;encrypt=true;trustServerCertificate=true
spring.datasource.username=nga
spring.datasource.password=12345a.
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.security.user.name=admin
spring.security.user.password=admin
management.security.enabled=false
logging.level.org.springframework.security=DEBUG
spring.jpa.properties.hibernate.format_sql=true